# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-21 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, upload_to='articles/')),
                ('bio', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=30)),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
